name: Release
on:
  push:
    tags:
      - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build release
      run: scripts/make_release.sh
      
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3.1
      env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
